parta : parta.c Makefile
	gcc -Wall -pthread parta.c -o parta

partb : partb.c Makefile
	gcc -Wall partb.c -o partb

partc : partc.c Makefile
	gcc -Wall partc.c -o partc

partd : partd.c Makefile
	gcc -Wall partd.c -o partd
