parta : parta.c Makefile
	gcc -Wall -pthread parta.c -o parta

partb : partb.c Makefile
	gcc -Wall -pthread partb.c -o partb

partc : partc.c Makefile
	gcc -Wall -pthread partc.c -o partc

partd : partd.c Makefile
	gcc -Wall -pthread partd.c -o partd
